/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import client.MyClient;
import domain.Student;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Yerlin Leal
 */
public class JIFRetrive extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFRetrive
     */
    private Student[] students;

    public JIFRetrive() {
        this.setVisible(false);
        initComponents();
        cleanTable();
        this.jlMessage.setForeground(Color.red);
        this.jlMessage.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jlMessage = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Retrive");

        jLabel1.setText("ID");

        jLabel2.setText("Name");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jlMessage.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jlMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlMessage)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.jtfId.getText().equals("") && this.jtfName.getText().equals("")) {
            this.jlMessage.setText("You must insert at least one data");
            cleanTable();
        } else {
            this.jlMessage.setText("");
            MyClient client = new MyClient();
            client.setAction("R");
            client.setMessage(this.jtfId.getText());
            client.setAux(this.jtfName.getText());
            client.start();
            while (true) {
                try {
                    if (client.getFinished()) {
                        break;
                    }
                    Thread.sleep(400);
                } catch (InterruptedException ex) {
                    Logger.getLogger(JIFRetrive.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            this.students = client.getStudents();
            loadTable();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private String[][] studentsString(Student s[]) {
        String studentsString[][] = new String[s.length][6];
        for (int i = 0; i < s.length; i++) {
            studentsString[i][0] = s[i].getId();
            studentsString[i][1] = s[i].getName();
            studentsString[i][2] = s[i].getLastname();
            studentsString[i][3] = String.valueOf(s[i].getAge());
            studentsString[i][4] = s[i].getTown();
            studentsString[i][5] = String.valueOf(s[i].getAdmissionGrade());
        }
        return studentsString;
    } // studentsString

    private void loadTable() {
        String studentsString[][] = studentsString(this.students);
        if (studentsString.length != 0) {
            this.jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    studentsString,
                    new String[]{"ID", "Name", "Lastname", "Age", "Town", "AdmissionGrade"}
            ));
        }else{
            cleanTable();
            this.jlMessage.setText("There are no records with this data");
        }
    } // loadTable
    
    private void cleanTable(){
        this.jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null}
                },
                new String[]{
                    "ID", "Name", "Lastname", "Age", "Town", "Admission Grade"
                }
        ));
    } // cleanTable

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlMessage;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfName;
    // End of variables declaration//GEN-END:variables
}
